const actions = {
    GET_ALBUMS_LIST_SUCCESS: 'GET_ALBUMS_LIST_SUCCESS',
    SET_TYPE: 'SET_TYPE',
    ADD_TAB: 'ADD_TAB',
    GET_SELECTED_ALBUM_SUCCESS: 'GET_SELECTED_ALBUM_SUCCESS',
    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',
    ADD_TO_QUEUE: 'ADD_TO_QUEUE',
    PLAYLIST_MODAL: 'PLAYLIST_MODAL',
    CREATE_PLAYLIST: 'CREATE_PLAYLIST',
}

export default actions;